django-journal/journal/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^todos/', include('todos.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

django-journal/todos/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    'todos.views',
    url(r'^$', 'index'),
    url(r'^(?P<todo_id>\d+)/$', 'detail'),
    url(r'^(?P<todo_id>\d+)/change/$', 'change')
)

django-journal/todos/models.py
import datetime
from django.utils import timezone
from django.db import models

class TodoList(models.Model):
    description = models.CharField(max_length=200)
    created_date = models.DateTimeField('Date created', auto_now_add=True)

    def __unicode__(self):
        return self.description

class LineItem(models.Model):
    description = models.CharField(max_length=200)
    created_date = models.DateTimeField('Date created', auto_now_add=True)
    my_list = models.ForeignKey(TodoList)
    is_done = models.BooleanField()

    def was_created_recently(self):
        return self.created_date >= timezone.now() - datetime.timedelta(days=1)

    def __unicode__(self):
        return self.description

django-journal/todos/forms.py
from django.forms import ModelForm

from todos.models import TodoList

class TodoListForm(ModelForm):
    class Meta:
        model = TodoList

django-journal/todos/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext

from todos.models import TodoList
from todos.forms import TodoListForm

def index(request):
    latest_todos_list = TodoList.objects.all().order_by('-created_date')[:5]
    return render_to_response('todos/index.html', {'latest_todos_list':latest_todos_list})

def detail(request, todo_id):
    todo_list = get_object_or_404(TodoList, pk=todo_id)
    form = TodoListForm(instance=todo_list)
    return render_to_response('todos/detail.html', {'todo':todo_list, 'form':form},
                              context_instance=RequestContext(request))

def change(request, todo_id):
    t = get_object_or_404(TodoList, pk=todo_id)
    if request.method == 'POST': # If the form has been submitted
        form = TodoListForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            print 'form is valid'
            # Process the data in form.cleaned_data
            print form
            return HttpResponseRedirect(reverse('todos.views.thanks'))
        else:
            print 'form not valid'
    else:
        form = TodoListForm()
    response_dict = {'todo':t, 'form': form}
    return render_to_response(
        'todos/change.html',
        response_dict,
        context_instance=RequestContext(request))

    # try:
    #     selected_items = 1
    # except (KeyError, LineItem.DoesNotExist):
    #     return render_to_response('todos/detail.html',
    #                               {'todo':t,
    #                                'error_message':'Invalid choice selection.'},
    #                               context_instance=RequestContext(request))
    # else:
    #     selected_items = 2
    #     # Always return an HttpResponseRedirect after successfully dealing
    #     # with POST data. This prevents data from being posted twice if a
    #     # user hits the Back button.
    #     return HttpResponseRedirect(reverse('todos.views.index'))
                                  

templates/snippets/form_element.html
{% for field in form %}
  {{ field.errors }}
  {{ field.label_tag }}:{{ field }}
{% endfor %}

templates/todos/change.html
<h1>{{ todo.description }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="/todos/{{ todo.id }}/change/" method="post">
  {% include "snippets/form_element.html" %}
  <p><input type="submit" value="Change" /></p>
</form>

templates/todos/detail.html
<h1>{{ todo.description }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if form.non_field_errors %}
  <p>{{ form.non_field_errors }}</p>
{% endif %}

<form action="/todos/{{ todo.id }}/change/" method="post">
  {% csrf_token %}
  {% for line_item in todo.lineitem_set.all %}
    <input type="checkbox" name="{{ todo.description|slugify }}-item-{{ line_item.id }}"
           id="{{ todo.description|slugify }}-item-{{ line_item.id }}" value="{{ line_item.id }}"
           {% if line_item.is_done %} checked="checked" {% endif %} />
    <label for="{{ todo.description|slugify }}-item-{{ line_item.id }}">
      {{ line_item.description|title }}
    </label>
  {% endfor %}
  <input type="submit" value="Change" />
</form>

templates/todos/index.html
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="To do list main page">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    </head>
    <body>
        <p>Hello world! This is HTML5 Boilerplate.</p>
        {% if latest_todos_list %}
          <ul>
            {% for todo in latest_todos_list %}
              <li><a href="/todos/{{ todo.id }}/"> {{ todo.description }}</a></li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No Todos are available.</p>
        {% endif %}
    </body>
</html>